# Generated by Django 5.1.7 on 2025-03-31 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_featureproducts_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Feature'},
        ),
    ]
