# Generated by Django 5.1.7 on 2025-03-31 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_feature_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='Features',
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Features', 'verbose_name_plural': 'Features'},
        ),
    ]
