# Generated by Django 5.1.7 on 2025-03-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_features_feature_alter_feature_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
