# Generated by Django 5.1.7 on 2025-03-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_feature_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='image_url',
        ),
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='features/'),
        ),
    ]
