# Generated by Django 5.1.7 on 2025-03-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='features/'),
        ),
    ]
